---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: orbital
# description will be included in the image's metadata
description: Fedora COSMIC Atomic base with niri (primary) + Noctalia shell

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/niri:latest
image-version: 43 # latest is also supported if you want new updates ASAP
